services:
  server:
    image: ecopharmai-server:latest
    build:
      context: ./server/ecopharmai
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/hello"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
  client:
    image: ecopharmai-client:latest
    build:
      context: ./client/ecopharmai
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL:-http://localhost:8080}
    depends_on:
      - server
    restart: unless-stopped
